version: '3.2'
services:
  api:
    build: .
    environment:
      - PORT=5000
  cypress:
    image: "cypress/included:4.4.0"
    depends_on:
      - api
    entrypoint: /scripts/wait_for_it.sh api:5000 -- cypress run
    environment:
      - CYPRESS_baseUrl=http://api:5000
    working_dir: /e2e
    volumes:
      - ./:/e2e